# Autopilot
# CARLA_ROOT: 'D:/Code/carla/CARLA_0.9.15'
MATS_ROOT: '/home/hjh/carla/Gym/mats-gym'

# PYTHONPATH: ''
# PYTHONPATH: '%PYTHONPATH%;%CARLA_ROOT%/PythonAPI;%CARLA_ROOT%/PythonAPI/carla'

SCENARIOS: '%WORK_DIR%/leaderboard/data/scenarios/eval_scenarios.json'
ROUTES: '%MATS_ROOT%/scenarios/routes/training.xml'
REPETITIONS: '1'
CHALLENGE_TRACK_CODENAME: 'SENSORS'
CHECKPOINT_ENDPOINT: '%WORK_DIR%/results/transfuser_plus_plus_longest6.json'
TEAM_AGENT: '%MATS_ROOT%/examples/example_agents/autopilot.py'
AGENT_CONFIG: 'hero' # pass to role_name
DEBUG_CHALLENGE: '0'
RESUME: '1'
DATAGEN: '0'
SAVE_PATH: '%WORK_DIR%/results'

UNCERTAINTY_THRESHOLD: '0.33'
BENCHMARK: 'longest6'